name : Flask CI

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requirements.txt

      - name: Print debugging information
        run: |
          echo "Python Version : ${python --version}"
          echo "Working directory : $(pwd)"
          echo "Conents of working directory : $(ls -l)"

      - name: Run tests
        run: python test_file.py
        



















      
          
          

  
